language: minimal
script:
    - script/build.sh
deploy:
    - provider: releases
      api_key:
          secure: "SYuwh2e7xRS9VTYpbXxzeiIyYBdnJAkNc9Ud7MlJomPobVDIpR0/s6WL5maK9pVDYFrrWBpwdwBh3vrOlCTuRh5Q/Sq9yL92YDawvWjPLPT3q0W6YNUDwcEia++cLOYHSH80PmsiwkXZztpwH2/00z33BBvj611MnjIwNsdMc0KZzLjKUeRRrwllK2VwIG5jYtgSv5LBjPnneEHuTNMkT5UVtV+fq/8AQCqig4Qs2zCJK/3x72LKOwQ9gtQxA8bv0KW5bIhynUOnNQDox+6V6KXkK+kVqFf0ADGTMCnFLtO/6EzUx+6qS55La51tW0kYzt0nRKCBaTvY2z9c7bQBnU33boEv/rGhh1G3XS2ALjSzQdzO/VHy2NZCEM/63AxLweKIWD0RXtIilFSFKkg4wmUsxyEMQWsYDGlKz9dyO2ZD/z7uKCyaaj8V5doec5BIAO/OXQhlVa4rN1bqwVifsmqu3uTWTUFY0JsLdxRi6w04SGhreYMX/y6nf+PxooqLd6y1r3zkA2Hb7NuTRwicCmQ0LPYfFJhf5uqUxQcDrVcuaV1dJKfoeFbVEMFGLEGr+vjN9f0vXRPC1DunmrYyOQMwXzngDJg2Uuvpgs/RxQm7iks1UzQLxFbmroBArTd9oKmvXqESw/ZfKJ0y2TL1SJ2CwvhTAjK3VZT365bLhP8="
      file: dist/rules.txt
      skip_cleanup: true
      on:
          tags: true
